-- Current Comptoir SQLite baseline.
-- Generated by: bun packages/api/scripts/db-baseline.ts generate
-- Do not edit manually; update through migrations, then regenerate.
PRAGMA foreign_keys = OFF;

CREATE TABLE IF NOT EXISTS __migrations (
      name TEXT PRIMARY KEY,
      applied_at TEXT NOT NULL DEFAULT (datetime('now'))
    );

CREATE TABLE admin_alerts (
  id TEXT PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id),
  recipient_id TEXT NOT NULL REFERENCES users(id),    -- the admin/manager who should see this
  type TEXT NOT NULL,                                  -- e.g. "dossier_completed"
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  action_url TEXT,                                     -- in-app link (e.g. /staff/<id>)
  worker_id TEXT REFERENCES users(id),                 -- subject of the alert when relevant
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  seen_at TEXT
);

CREATE TABLE `audit_logs` (
  `id` text PRIMARY KEY NOT NULL,
  `restaurant_id` text NOT NULL REFERENCES `restaurants`(`id`),
  `table_name` text NOT NULL,
  `row_id` text NOT NULL,
  `action` text NOT NULL,
  `actor_id` text REFERENCES `users`(`id`),
  `actor_name` text,
  `source` text NOT NULL,
  `changes` text,
  `summary` text,
  `created_at` text NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE calendar_events (
  id TEXT PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id),
  type TEXT NOT NULL, -- 'public_holiday' | 'school_vacation'
  date TEXT NOT NULL, -- YYYY-MM-DD
  end_date TEXT, -- YYYY-MM-DD (vacations only)
  name TEXT NOT NULL,
  zone TEXT, -- 'metropole'/'alsace-moselle' or 'A'/'B'/'C'
  year INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE chat_messages (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  role TEXT NOT NULL CHECK(role IN ('user', 'assistant', 'tool')),
  content TEXT NOT NULL,
  tool_calls TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
, owner_id TEXT REFERENCES owners(id), restaurant_id TEXT REFERENCES restaurants(id), context_kind TEXT);

CREATE TABLE contract_templates (
  id TEXT PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id),
  kind TEXT NOT NULL CHECK (kind IN ('CDI', 'CDD', 'saisonnier', 'extra')),
  name TEXT NOT NULL,
  body_html TEXT NOT NULL,          -- mustache-style {{token}} substitution
  is_default INTEGER NOT NULL DEFAULT 0,  -- owner-marked "use this by default for the kind"
  created_by TEXT REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE cron_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  job_name TEXT NOT NULL,
  attempt INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL CHECK (status IN ('running', 'ok', 'error')),
  started_at TEXT NOT NULL DEFAULT (datetime('now')),
  finished_at TEXT,
  duration_ms INTEGER,
  error TEXT,
  result TEXT
, owner_id TEXT REFERENCES owners(id), scope TEXT);

CREATE TABLE `daily_revenue` (
	`id` text PRIMARY KEY NOT NULL,
	`restaurant_id` text NOT NULL,
	`date` text NOT NULL,
	`amount` integer NOT NULL,
	`notes` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	FOREIGN KEY (`restaurant_id`) REFERENCES `restaurants`(`id`) ON UPDATE no action ON DELETE no action
);

CREATE TABLE `documents` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`restaurant_id` text NOT NULL,
	`name` text NOT NULL,
	`type` text NOT NULL,
	`filename` text NOT NULL,
	`mime_type` text NOT NULL,
	`size` integer NOT NULL,
	`data` text NOT NULL,
	`uploaded_by` text NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL, `holiday_request_id` text REFERENCES holiday_requests(id), requirement_key TEXT, issued_at TEXT, expires_at TEXT, signed_at TEXT, replacement_request_id TEXT REFERENCES "replacement_requests"(id), storage_provider TEXT, storage_key TEXT, storage_status TEXT NOT NULL DEFAULT 'ready', reviewed_at TEXT, reviewed_by TEXT REFERENCES users(id),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`restaurant_id`) REFERENCES `restaurants`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`uploaded_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);

CREATE TABLE `email_recipients` (
  `id` text PRIMARY KEY NOT NULL,
  `restaurant_id` text NOT NULL REFERENCES `restaurants`(`id`),
  `label` text NOT NULL,
  `email` text NOT NULL,
  `send_monthly_digest` integer NOT NULL DEFAULT 0,
  `send_leave_alerts` integer NOT NULL DEFAULT 0,
  `created_at` text NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE `holiday_requests` (
	`id` text PRIMARY KEY NOT NULL,
	`worker_id` text NOT NULL,
	`restaurant_id` text NOT NULL,
	`start_date` text NOT NULL,
	`end_date` text NOT NULL,
	`reason` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`reviewed_by` text,
	`reviewed_at` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL, `medical` integer DEFAULT false NOT NULL, `source` text NOT NULL DEFAULT 'worker',
	FOREIGN KEY (`worker_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`restaurant_id`) REFERENCES `restaurants`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`reviewed_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);

CREATE TABLE legal_acceptances (
  id TEXT PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id),
  user_id TEXT NOT NULL REFERENCES users(id),
  acceptance_type TEXT NOT NULL CHECK (acceptance_type IN ('owner_terms')),
  terms_version TEXT NOT NULL,
  dpa_version TEXT NOT NULL,
  privacy_version TEXT NOT NULL,
  subprocessors_version TEXT NOT NULL,
  ip_address TEXT,
  user_agent TEXT,
  accepted_at TEXT NOT NULL DEFAULT (datetime('now')),
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
, `owner_id` TEXT REFERENCES `owners`(`id`));

CREATE TABLE `notifications` (
	`id` text PRIMARY KEY NOT NULL,
	`recipient_id` text NOT NULL,
	`type` text NOT NULL,
	`channel` text DEFAULT 'whatsapp' NOT NULL,
	`message` text NOT NULL,
	`status` text DEFAULT 'queued' NOT NULL,
	`scheduled_for` text NOT NULL,
	`sent_at` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL, owner_id TEXT REFERENCES owners(id), restaurant_id TEXT REFERENCES restaurants(id),
	FOREIGN KEY (`recipient_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);

CREATE TABLE onboarding_tokens (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  token TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at TEXT NOT NULL
, restaurant_id text REFERENCES restaurants(id));

CREATE TABLE open_shifts (
  id TEXT PRIMARY KEY NOT NULL,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id),
  created_by TEXT NOT NULL REFERENCES users(id),
  date TEXT NOT NULL,                      -- YYYY-MM-DD
  start_time TEXT NOT NULL,                -- HH:MM
  end_time TEXT NOT NULL,                  -- HH:MM
  role TEXT NOT NULL,                      -- kitchen | floor (validated app-side)
  required_sub_roles TEXT NOT NULL DEFAULT '[]',  -- JSON array
  message TEXT,                            -- admin context, e.g. "ce soir busy night"
  candidate_ids TEXT NOT NULL DEFAULT '[]',       -- JSON array (ranked at creation)
  rejected_candidate_ids TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'open',     -- open | claimed | cancelled | expired
  claimed_by TEXT REFERENCES users(id),
  claimed_at TEXT,
  service_id TEXT REFERENCES services(id), -- created on claim, NULL until then
  expires_at TEXT NOT NULL,                -- typically date+startTime
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
, solicited_candidate_ids TEXT NOT NULL DEFAULT '[]', last_solicited_at TEXT);

CREATE TABLE `owner_memberships` (
  `owner_id` TEXT NOT NULL REFERENCES `owners`(`id`),
  `user_id` TEXT NOT NULL REFERENCES `users`(`id`),
  `role` TEXT NOT NULL,
  `created_at` TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (`owner_id`, `user_id`)
);

CREATE TABLE `owners` (
  `id` TEXT PRIMARY KEY NOT NULL,
  `name` TEXT NOT NULL,
  `stripe_customer_id` TEXT,
  `stripe_subscription_id` TEXT,
  `subscription_status` TEXT NOT NULL DEFAULT 'active',
  `subscription_period_end` TEXT,
  `trial_ends_at` TEXT,
  `cancel_at` TEXT,
  `created_at` TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE password_reset_tokens (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id),
  token TEXT NOT NULL UNIQUE,
  used INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at TEXT NOT NULL
);

CREATE TABLE pending_registrations (
  id TEXT PRIMARY KEY,
  restaurant_name TEXT NOT NULL,
  admin_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  stripe_session_id TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  expires_at TEXT NOT NULL
);

CREATE TABLE `published_weeks` (
  `id` text PRIMARY KEY NOT NULL,
  `restaurant_id` text NOT NULL REFERENCES `restaurants`(`id`),
  `week_date` text NOT NULL,
  `published_at` text NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE "replacement_requests" (
  id TEXT PRIMARY KEY,
  requester_id TEXT NOT NULL REFERENCES users(id),
  requester_service_id TEXT NOT NULL REFERENCES services(id),
  target_id TEXT REFERENCES users(id),
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id),
  status TEXT NOT NULL DEFAULT 'awaiting_owner_decision',
  message TEXT,
  responded_at TEXT,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  candidate_ids TEXT,
  candidate_scores TEXT,
  admin_notified_at TEXT,
  worker_notified_at TEXT,
  escalation_count INTEGER NOT NULL DEFAULT 0,
  rejected_candidate_ids TEXT NOT NULL DEFAULT '[]'
, medical INTEGER NOT NULL DEFAULT 0, itt_reminder_sent_at TEXT);

CREATE TABLE `restaurant_closures` (
	`id` text PRIMARY KEY NOT NULL,
	`restaurant_id` text NOT NULL,
	`start_date` text NOT NULL,
	`end_date` text NOT NULL,
	`reason` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL, `schedule` text,
	FOREIGN KEY (`restaurant_id`) REFERENCES `restaurants`(`id`) ON UPDATE no action ON DELETE no action
);

CREATE TABLE `restaurant_memberships` (
  `restaurant_id` TEXT NOT NULL REFERENCES `restaurants`(`id`),
  `user_id` TEXT NOT NULL REFERENCES `users`(`id`),
  `role` TEXT NOT NULL,
  `permissions` TEXT,
  `active` INTEGER NOT NULL DEFAULT 1,
  `created_at` TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (`restaurant_id`, `user_id`)
);

CREATE TABLE "restaurants" (
  `id` text PRIMARY KEY NOT NULL,
  `name` text NOT NULL,
  `timezone` text DEFAULT 'Europe/Paris' NOT NULL,
  `created_at` text DEFAULT (datetime('now')) NOT NULL,
  `open_days` text DEFAULT '[2,3,4,5,6,7]' NOT NULL,
  `medical_mode` integer DEFAULT 0 NOT NULL,
  `tap_in_out_enabled` INTEGER NOT NULL DEFAULT 1,
  `reminder_frequency` TEXT NOT NULL DEFAULT 'off',
  `color_scheme` TEXT NOT NULL DEFAULT 'classic',
  `worker_preferences_enabled` INTEGER NOT NULL DEFAULT 0,
  `auto_staffing_weeks` integer NOT NULL DEFAULT 0,
  `disabled_compliance_rules` TEXT NOT NULL DEFAULT '[]',
  `overtime_mode` TEXT NOT NULL DEFAULT 'flexible',
  `overtime_weekly_cap` INTEGER NOT NULL DEFAULT 48,
  `overtime_distribution` TEXT NOT NULL DEFAULT 'willing-first',
  `stripe_customer_id` TEXT,
  `stripe_subscription_id` TEXT,
  `status` TEXT NOT NULL DEFAULT 'active',
  `subscription_status` TEXT NOT NULL DEFAULT 'active',
  `subscription_period_end` TEXT,
  `trial_ends_at` TEXT,
  `cancel_at` TEXT,
  `latitude` REAL,
  `longitude` REAL,
  `address` TEXT,
  `school_zone` TEXT,
  `holiday_zone` TEXT,
  `kitchen_sub_roles` TEXT NOT NULL DEFAULT '["Chef","Sous-chef","Cuisinier","Plongeur"]',
  "floor_sub_roles" TEXT NOT NULL DEFAULT '["Chef de rang","Serveur","Runner","Barman"]',
  `kitchen_color` TEXT NOT NULL DEFAULT 'amber',
  "floor_color" TEXT NOT NULL DEFAULT 'sky',
  `hcr_grid` TEXT NOT NULL DEFAULT '{}',
  `subrole_hcr_map` TEXT NOT NULL DEFAULT '{}',
  `default_contract_type` TEXT NOT NULL DEFAULT 'CDI' CHECK (default_contract_type IN ('CDI','CDD','saisonnier')),
  `default_contract_hours` INTEGER NOT NULL DEFAULT 35,
  `preferred_style` TEXT NOT NULL DEFAULT 'equilibre'
    CHECK (preferred_style IN ('equilibre','equipe-stable','economique','resilience')),
  `custom_weights` TEXT
, `cache_version` integer NOT NULL DEFAULT 0, `revenue_per_covered_slot_cents` integer, onboarding_completed_at TEXT, tap_in_out_admin_confirmation INTEGER NOT NULL DEFAULT 0, tap_in_out_mode TEXT NOT NULL DEFAULT 'lateness_only', tap_in_counts_as_hours INTEGER NOT NULL DEFAULT 0, siret TEXT, whatsapp_bot_locale TEXT NOT NULL DEFAULT 'fr', cancellation_reason TEXT, cancellation_feedback TEXT, cancellation_comment TEXT, cancellation_requested_at TEXT, include_silae_in_monthly_digest INTEGER NOT NULL DEFAULT 0, silae_codes TEXT NOT NULL DEFAULT '{}', `owner_id` TEXT REFERENCES `owners`(`id`));

CREATE TABLE restriction_requests (
  id TEXT PRIMARY KEY,
  worker_id TEXT NOT NULL REFERENCES users(id),
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id),
  kind TEXT NOT NULL CHECK (kind IN ('permanent','temporary')),
  effective_from TEXT, -- YYYY-MM-DD, null for permanent
  effective_until TEXT, -- YYYY-MM-DD, null for permanent
  restrictions TEXT NOT NULL DEFAULT '[]', -- JSON: [{dayOfWeek, startTime, endTime, reason}]
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','cancelled')),
  note TEXT, -- worker's justification
  admin_note TEXT, -- owner's decision note
  reviewed_by TEXT REFERENCES users(id),
  reviewed_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE "service_template_overrides" (
  `id` text PRIMARY KEY NOT NULL,
  `template_id` text NOT NULL REFERENCES "service_templates"(`id`) ON DELETE CASCADE,
  `day_of_week` integer NOT NULL,
  `start_time` text NOT NULL,
  `end_time` text NOT NULL
);

CREATE TABLE "service_templates" (
	`id` text PRIMARY KEY NOT NULL,
	`restaurant_id` text NOT NULL,
	`role` text NOT NULL,
	`zone` text NOT NULL,
	`start_time` text NOT NULL,
	`end_time` text NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0, profile_id TEXT REFERENCES staffing_profiles(id),
	FOREIGN KEY (`restaurant_id`) REFERENCES `restaurants`(`id`) ON UPDATE no action ON DELETE no action
);

CREATE TABLE "services" (
	`id` text PRIMARY KEY NOT NULL,
	`worker_id` text NOT NULL,
	`restaurant_id` text NOT NULL,
	`date` text NOT NULL,
	`start_time` text NOT NULL,
	`end_time` text NOT NULL,
	`role` text NOT NULL,
	`status` text DEFAULT 'scheduled' NOT NULL,
	`notes` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL,
	`updated_at` text DEFAULT (datetime('now')) NOT NULL, `source` text NOT NULL DEFAULT 'manual', filled_as TEXT,
	FOREIGN KEY (`worker_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`restaurant_id`) REFERENCES `restaurants`(`id`) ON UPDATE no action ON DELETE no action
);

CREATE TABLE `sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`expires_at` text NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL, `active_restaurant_id` TEXT REFERENCES `restaurants`(`id`),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);

CREATE TABLE `staffing_analysis_cache` (
  `id` TEXT PRIMARY KEY NOT NULL,
  `restaurant_id` TEXT NOT NULL REFERENCES `restaurants`(`id`),
  `profile_id` TEXT,
  `horizon_weeks` INTEGER NOT NULL,
  `base_monday` TEXT NOT NULL,
  `cache_key` TEXT NOT NULL UNIQUE,
  `status` TEXT NOT NULL,
  `started_at` TEXT NOT NULL DEFAULT (datetime('now')),
  `finished_at` TEXT,
  `duration_ms` INTEGER,
  `result` TEXT,
  `error` TEXT
);

CREATE TABLE staffing_profiles (
  id TEXT PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id),
  name TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
, day_priorities TEXT NOT NULL DEFAULT '{}', preferred_assignments TEXT NOT NULL DEFAULT '[]');

CREATE TABLE staffing_schedule (
  id TEXT PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id),
  profile_id TEXT NOT NULL REFERENCES staffing_profiles(id),
  year INTEGER NOT NULL,
  week INTEGER NOT NULL,
  UNIQUE(restaurant_id, year, week)
);

CREATE TABLE "staffing_targets" (
  id TEXT PRIMARY KEY,
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id),
  profile_id TEXT REFERENCES staffing_profiles(id),
  day_of_week INTEGER NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('kitchen', 'floor')),
  zone TEXT NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  role_breakdown TEXT NOT NULL DEFAULT '{}',
  UNIQUE(restaurant_id, profile_id, day_of_week, role, zone)
);

CREATE TABLE `sub_role_training_costs` (
  `restaurant_id` text NOT NULL,
  `from_role` text NOT NULL,
  `to_role` text NOT NULL,
  `cost_points` real NOT NULL,
  `successes` integer NOT NULL DEFAULT 0,
  `failures` integer NOT NULL DEFAULT 0,
  `last_updated` integer NOT NULL,
  "admin_override" integer NOT NULL DEFAULT 0,
  PRIMARY KEY (`restaurant_id`, `from_role`, `to_role`)
);

CREATE TABLE `sub_role_training_moves` (
  `id` text PRIMARY KEY NOT NULL,
  `restaurant_id` text NOT NULL,
  `worker_id` text NOT NULL,
  `move_type` text NOT NULL,
  `from_role` text NOT NULL,
  `to_role` text NOT NULL,
  `applied_at` integer NOT NULL,
  `observed_at` integer,
  `outcome` text
);

CREATE TABLE `time_clocks` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`restaurant_id` text NOT NULL,
	"service_id" text,
	`tap_in` text NOT NULL,
	`tap_out` text,
	`date` text NOT NULL,
	`created_at` text DEFAULT (datetime('now')) NOT NULL, admin_confirmed_at TEXT, admin_confirmed_by TEXT REFERENCES users(id),
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`restaurant_id`) REFERENCES `restaurants`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY ("service_id") REFERENCES "services"(`id`) ON UPDATE no action ON DELETE no action
);

CREATE TABLE "users" (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`phone` text NOT NULL,
	`password_hash` text NOT NULL,
	`role` text NOT NULL,
	`restaurant_id` text NOT NULL,
	`priority` integer DEFAULT 1 NOT NULL,
	`address` text,
	`iban` text,
	`start_date` text,
	`emergency_contact` text,
	`emergency_phone` text,
	`notes` text,
	`manager_notes` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL, overtime_willing INTEGER NOT NULL DEFAULT 0, matricule TEXT, active INTEGER NOT NULL DEFAULT 1, contract_type TEXT, contract_hours INTEGER, sub_role TEXT, sub_roles TEXT NOT NULL DEFAULT '[]', inactive_from TEXT, inactive_until TEXT, contract_end_date TEXT, max_weekly_hours INTEGER, admin_ot_override INTEGER, coupure_willing INTEGER NOT NULL DEFAULT 0, multi_restaurant_willing INTEGER NOT NULL DEFAULT 1, hcr_level TEXT, hourly_rate INTEGER, rate_effective_from TEXT, `must_change_password` INTEGER NOT NULL DEFAULT 0, first_name TEXT, last_name TEXT, permissions TEXT, date_of_birth TEXT, birth_place TEXT, nationality TEXT, nir TEXT, address_street TEXT, address_postal_code TEXT, address_city TEXT, last_dossier_reminder_at TEXT, user_notice_version TEXT, user_notice_accepted_at TEXT, user_notice_ip_address TEXT, user_notice_user_agent TEXT, whatsapp_opt_in INTEGER NOT NULL DEFAULT 0, whatsapp_opt_in_at TEXT, whatsapp_opt_out_at TEXT,
	FOREIGN KEY (`restaurant_id`) REFERENCES `restaurants`(`id`) ON UPDATE no action ON DELETE no action
);

CREATE TABLE weather_data (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id),
  date TEXT NOT NULL,
  -- Daily summary
  weather_code INTEGER,           -- WMO weather code (0=clear, 1-3=clouds, 45-48=fog, 51-67=rain, 71-77=snow, 80-82=showers, 95-99=thunderstorm)
  temp_max REAL,                  -- °C
  temp_min REAL,                  -- °C
  sunrise TEXT,                   -- HH:MM
  sunset TEXT,                    -- HH:MM
  -- Seasonal normals for comparison
  normal_temp_max REAL,           -- °C — average of same date over past 5 years
  normal_temp_min REAL,           -- °C
  -- Hourly data as JSON arrays (24 entries, index 0 = 00:00)
  hourly_weather_codes TEXT,      -- JSON: [0, 0, 1, 2, 3, 61, ...]
  hourly_temperatures TEXT,       -- JSON: [8.2, 7.5, 7.1, ...]
  -- Source tracking
  is_forecast INTEGER NOT NULL DEFAULT 1,  -- 1=forecast, 0=confirmed historical
  fetched_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(restaurant_id, date)
);

CREATE TABLE `whatsapp_context_sessions` (
  `phone` TEXT PRIMARY KEY NOT NULL,
  `user_id` TEXT NOT NULL REFERENCES `users`(`id`),
  `restaurant_id` TEXT NOT NULL REFERENCES `restaurants`(`id`),
  `selected_at` TEXT NOT NULL DEFAULT (datetime('now')),
  `expires_at` TEXT NOT NULL
);

CREATE TABLE `worker_availability` (
	`id` text PRIMARY KEY NOT NULL,
	`worker_id` text NOT NULL,
	`restaurant_id` text NOT NULL,
	`day_of_week` integer NOT NULL,
	`midi` integer DEFAULT false NOT NULL,
	`soir` integer DEFAULT false NOT NULL, midi_start TEXT, midi_end TEXT, soir_start TEXT, soir_end TEXT, continuous INTEGER NOT NULL DEFAULT 0, zones TEXT NOT NULL DEFAULT '{}',
	FOREIGN KEY (`worker_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`restaurant_id`) REFERENCES `restaurants`(`id`) ON UPDATE no action ON DELETE no action
);

CREATE TABLE worker_preferred_schedule (
  id TEXT PRIMARY KEY,
  worker_id TEXT NOT NULL REFERENCES users(id),
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id),
  day_of_week INTEGER NOT NULL,
  midi INTEGER NOT NULL DEFAULT 0,
  soir INTEGER NOT NULL DEFAULT 0
, zones TEXT NOT NULL DEFAULT '{}');

CREATE TABLE `worker_restaurant_profiles` (
  `restaurant_id` TEXT NOT NULL REFERENCES `restaurants`(`id`),
  `user_id` TEXT NOT NULL REFERENCES `users`(`id`),
  `priority` INTEGER NOT NULL DEFAULT 1,
  `sub_roles` TEXT NOT NULL DEFAULT '[]',
  `contract_type` TEXT,
  `contract_hours` INTEGER,
  `contract_end_date` TEXT,
  `max_weekly_hours` INTEGER,
  `admin_ot_override` INTEGER,
  `hcr_level` TEXT,
  `hourly_rate` INTEGER,
  `matricule` TEXT,
  `manager_notes` TEXT,
  `multi_restaurant_willing` INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (`restaurant_id`, `user_id`)
);

CREATE TABLE worker_restrictions (
  id TEXT PRIMARY KEY,
  worker_id TEXT NOT NULL REFERENCES users(id),
  restaurant_id TEXT NOT NULL REFERENCES restaurants(id),
  day_of_week INTEGER NOT NULL,  -- 1=Mon, 7=Sun
  start_time TEXT,               -- HH:MM or NULL for full day
  end_time TEXT,                 -- HH:MM or NULL for full day
  reason TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
, effective_from TEXT, effective_until TEXT);

CREATE TABLE `worker_share_authorizations` (
  `id` TEXT PRIMARY KEY NOT NULL,
  `owner_id` TEXT NOT NULL REFERENCES `owners`(`id`),
  `source_restaurant_id` TEXT NOT NULL REFERENCES `restaurants`(`id`),
  `target_restaurant_id` TEXT NOT NULL REFERENCES `restaurants`(`id`),
  `user_id` TEXT NOT NULL REFERENCES `users`(`id`),
  `role` TEXT NOT NULL,
  `status` TEXT NOT NULL DEFAULT 'pending',
  `invited_by_user_id` TEXT NOT NULL REFERENCES `users`(`id`),
  `worker_consented_at` TEXT,
  `revoked_at` TEXT,
  `created_at` TEXT NOT NULL DEFAULT (datetime('now')),
  `updated_at` TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE `worker_weekly_hours` (
  `worker_id` text NOT NULL,
  `week_start` text NOT NULL,
  `hours_actual` real NOT NULL,
  `recorded_at` integer NOT NULL,
  `source` text NOT NULL DEFAULT 'services',
  PRIMARY KEY (`worker_id`, `week_start`)
);

CREATE INDEX admin_alerts_recipient_unseen_idx ON admin_alerts(recipient_id, seen_at);

CREATE INDEX contract_templates_restaurant_idx
  ON contract_templates(restaurant_id, kind);

CREATE INDEX `email_recipients_restaurant_idx`
  ON `email_recipients` (`restaurant_id`);

CREATE INDEX `holiday_requests_worker_pending_idx`
  ON `holiday_requests` (`worker_id`, `status`, `source`);

CREATE INDEX `idx_audit_logs_restaurant_created` ON `audit_logs` (`restaurant_id`, `created_at`);

CREATE INDEX `idx_audit_logs_table_row` ON `audit_logs` (`table_name`, `row_id`);

CREATE INDEX idx_calendar_events_restaurant_date ON calendar_events(restaurant_id, date);

CREATE INDEX idx_cron_runs_job_started ON cron_runs(job_name, started_at DESC);

CREATE UNIQUE INDEX `idx_legal_acceptances_owner_terms_version`
  ON `legal_acceptances` (
    `owner_id`,
    `acceptance_type`,
    `terms_version`,
    `dpa_version`,
    `privacy_version`,
    `subprocessors_version`
  )
  WHERE `owner_id` IS NOT NULL;

CREATE INDEX `idx_legal_acceptances_owner_type` ON `legal_acceptances` (`owner_id`, `acceptance_type`);

CREATE INDEX idx_onboarding_tokens_restaurant_id ON onboarding_tokens(restaurant_id);

CREATE INDEX idx_open_shifts_restaurant_status ON open_shifts(restaurant_id, status);

CREATE INDEX `idx_owner_memberships_user` ON `owner_memberships` (`user_id`);

CREATE INDEX `idx_restaurant_memberships_user` ON `restaurant_memberships` (`user_id`, `active`);

CREATE INDEX `idx_restaurants_owner_id` ON `restaurants` (`owner_id`);

CREATE INDEX idx_restriction_requests_restaurant ON restriction_requests(restaurant_id, status);

CREATE INDEX idx_restriction_requests_worker ON restriction_requests(worker_id, status);

CREATE INDEX `idx_sessions_active_restaurant_id` ON `sessions` (`active_restaurant_id`);

CREATE INDEX `idx_staffing_analysis_cache_restaurant`
  ON `staffing_analysis_cache` (`restaurant_id`, `horizon_weeks`, `base_monday`);

CREATE INDEX `idx_sub_role_training_moves_applied_at` ON `sub_role_training_moves`(`applied_at`);

CREATE INDEX `idx_sub_role_training_moves_restaurant` ON `sub_role_training_moves`(`restaurant_id`);

CREATE INDEX `idx_whatsapp_context_sessions_expires_at`
  ON `whatsapp_context_sessions` (`expires_at`);

CREATE INDEX idx_worker_restrictions_worker ON worker_restrictions(worker_id, restaurant_id);

CREATE INDEX `idx_worker_share_authorizations_owner_target`
ON `worker_share_authorizations` (`owner_id`, `target_restaurant_id`, `status`);

CREATE UNIQUE INDEX `idx_worker_share_authorizations_unique_active`
ON `worker_share_authorizations` (`target_restaurant_id`, `user_id`, `role`)
WHERE `status` IN ('pending', 'accepted');

CREATE INDEX `idx_worker_share_authorizations_worker`
ON `worker_share_authorizations` (`user_id`, `status`);

CREATE INDEX `idx_worker_weekly_hours_week` ON `worker_weekly_hours`(`week_start`);

CREATE INDEX `idx_worker_weekly_hours_worker` ON `worker_weekly_hours`(`worker_id`);

CREATE UNIQUE INDEX legal_acceptances_owner_terms_version_idx
  ON legal_acceptances(restaurant_id, acceptance_type, terms_version, dpa_version, privacy_version, subprocessors_version);

CREATE INDEX legal_acceptances_restaurant_type_idx ON legal_acceptances(restaurant_id, acceptance_type);

CREATE INDEX onboarding_tokens_user_idx ON onboarding_tokens(user_id);

CREATE INDEX `published_weeks_resto_week_idx`
  ON `published_weeks` (`restaurant_id`, `week_date`);

CREATE UNIQUE INDEX `shift_template_overrides_template_day` ON "service_template_overrides" (`template_id`, `day_of_week`);

CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);

DELETE FROM __migrations;
INSERT INTO __migrations (name) VALUES ('0000_flawless_princess_powerful.sql');
INSERT INTO __migrations (name) VALUES ('0001_quick_shen.sql');
INSERT INTO __migrations (name) VALUES ('0002_powerful_psylocke.sql');
INSERT INTO __migrations (name) VALUES ('0003_lonely_human_fly.sql');
INSERT INTO __migrations (name) VALUES ('0004_elite_tyger_tiger.sql');
INSERT INTO __migrations (name) VALUES ('0005_damp_eternity.sql');
INSERT INTO __migrations (name) VALUES ('0006_third_vindicator.sql');
INSERT INTO __migrations (name) VALUES ('0007_natural_beast.sql');
INSERT INTO __migrations (name) VALUES ('0008_brown_silver_surfer.sql');
INSERT INTO __migrations (name) VALUES ('0009_loving_the_leader.sql');
INSERT INTO __migrations (name) VALUES ('0010_owner_preferences.sql');
INSERT INTO __migrations (name) VALUES ('0011_color_scheme.sql');
INSERT INTO __migrations (name) VALUES ('0012_worker_custom_times.sql');
INSERT INTO __migrations (name) VALUES ('0013_worker_preferred_schedule.sql');
INSERT INTO __migrations (name) VALUES ('0014_worker_preferences_enabled.sql');
INSERT INTO __migrations (name) VALUES ('0015_auto_staffing_weeks.sql');
INSERT INTO __migrations (name) VALUES ('0016_staffing_targets.sql');
INSERT INTO __migrations (name) VALUES ('0017_compliance_rules_toggle.sql');
INSERT INTO __migrations (name) VALUES ('0018_chef_designation.sql');
INSERT INTO __migrations (name) VALUES ('0019_overtime_willing.sql');
INSERT INTO __migrations (name) VALUES ('0020_overtime_policy.sql');
INSERT INTO __migrations (name) VALUES ('0020_stripe_registration.sql');
INSERT INTO __migrations (name) VALUES ('0021_matricule.sql');
INSERT INTO __migrations (name) VALUES ('0022_subscription_lifecycle.sql');
INSERT INTO __migrations (name) VALUES ('0023_cancel_at.sql');
INSERT INTO __migrations (name) VALUES ('0025_user_soft_delete.sql');
INSERT INTO __migrations (name) VALUES ('0026_chat_messages.sql');
INSERT INTO __migrations (name) VALUES ('0027_dynamic_shift_zones.sql');
INSERT INTO __migrations (name) VALUES ('0028_free_staffing_targets_zone.sql');
INSERT INTO __migrations (name) VALUES ('0029_availability_zones_json.sql');
INSERT INTO __migrations (name) VALUES ('0030_weather_data.sql');
INSERT INTO __migrations (name) VALUES ('0031_staffing_profiles.sql');
INSERT INTO __migrations (name) VALUES ('0032_staffing_targets_profile_unique.sql');
INSERT INTO __migrations (name) VALUES ('0033_staffing_schedule.sql');
INSERT INTO __migrations (name) VALUES ('0034_shift_templates_profile_id.sql');
INSERT INTO __migrations (name) VALUES ('0035_restaurant_address.sql');
INSERT INTO __migrations (name) VALUES ('0036_calendar_events.sql');
INSERT INTO __migrations (name) VALUES ('0037_swap_broadcast.sql');
INSERT INTO __migrations (name) VALUES ('0038_shift_source.sql');
INSERT INTO __migrations (name) VALUES ('0039_shift_template_overrides.sql');
INSERT INTO __migrations (name) VALUES ('0040_audit_logs.sql');
INSERT INTO __migrations (name) VALUES ('0041_rename_shift_to_service.sql');
INSERT INTO __migrations (name) VALUES ('0042_fix_staffing_targets_role_constraint.sql');
INSERT INTO __migrations (name) VALUES ('0043_contract_fields.sql');
INSERT INTO __migrations (name) VALUES ('0044_reset_default_availability.sql');
INSERT INTO __migrations (name) VALUES ('0045_worker_restrictions.sql');
INSERT INTO __migrations (name) VALUES ('0046_split_chef_requirement.sql');
INSERT INTO __migrations (name) VALUES ('0047_chef_required_zones.sql');
INSERT INTO __migrations (name) VALUES ('0048_sous_chef.sql');
INSERT INTO __migrations (name) VALUES ('0049_day_priorities.sql');
INSERT INTO __migrations (name) VALUES ('0050_role_based_staffing.sql');
INSERT INTO __migrations (name) VALUES ('0051_role_based_per_profile.sql');
INSERT INTO __migrations (name) VALUES ('0052_user_sub_roles.sql');
INSERT INTO __migrations (name) VALUES ('0053_sub_role_mode.sql');
INSERT INTO __migrations (name) VALUES ('0054_temp_deactivation.sql');
INSERT INTO __migrations (name) VALUES ('0055_independent_color_palettes.sql');
INSERT INTO __migrations (name) VALUES ('0056_contract_end_date.sql');
INSERT INTO __migrations (name) VALUES ('0057_max_weekly_hours.sql');
INSERT INTO __migrations (name) VALUES ('0058_owner_ot_override.sql');
INSERT INTO __migrations (name) VALUES ('0059_coupure_multi_resto.sql');
INSERT INTO __migrations (name) VALUES ('0060_restriction_requests.sql');
INSERT INTO __migrations (name) VALUES ('0061_hcr_grid_and_hourly_rate.sql');
INSERT INTO __migrations (name) VALUES ('0062_preferred_style.sql');
INSERT INTO __migrations (name) VALUES ('0063_custom_weights.sql');
INSERT INTO __migrations (name) VALUES ('0064_document_checklist.sql');
INSERT INTO __migrations (name) VALUES ('0065_contract_templates.sql');
INSERT INTO __migrations (name) VALUES ('0066_document_signed_at.sql');
INSERT INTO __migrations (name) VALUES ('0067_rate_effective_from.sql');
INSERT INTO __migrations (name) VALUES ('0068_unify_staffing_role_model.sql');
INSERT INTO __migrations (name) VALUES ('0069_published_weeks.sql');
INSERT INTO __migrations (name) VALUES ('0070_must_change_password.sql');
INSERT INTO __migrations (name) VALUES ('0071_hourly_rate_cents.sql');
INSERT INTO __migrations (name) VALUES ('0072_preferred_style_v2.sql');
INSERT INTO __migrations (name) VALUES ('0073_drop_flexibilite_preset.sql');
INSERT INTO __migrations (name) VALUES ('0074_email_recipients.sql');
INSERT INTO __migrations (name) VALUES ('0075_holiday_source.sql');
INSERT INTO __migrations (name) VALUES ('0076_cache_version.sql');
INSERT INTO __migrations (name) VALUES ('0077_worker_weekly_hours.sql');
INSERT INTO __migrations (name) VALUES ('0078_revenue_per_covered_slot.sql');
INSERT INTO __migrations (name) VALUES ('0079_sub_role_training_costs.sql');
INSERT INTO __migrations (name) VALUES ('0080_replacement_flow.sql');
INSERT INTO __migrations (name) VALUES ('0081_replacement_medical.sql');
INSERT INTO __migrations (name) VALUES ('0082_services_filled_as.sql');
INSERT INTO __migrations (name) VALUES ('0083_staffing_profile_titulaires.sql');
INSERT INTO __migrations (name) VALUES ('0084_staffing_profile_assignments.sql');
INSERT INTO __migrations (name) VALUES ('0085_onboarding_completed_at.sql');
INSERT INTO __migrations (name) VALUES ('0086_user_first_last_name.sql');
INSERT INTO __migrations (name) VALUES ('0087_drop_role_based_staffing.sql');
INSERT INTO __migrations (name) VALUES ('0088_drop_swap_toggles.sql');
INSERT INTO __migrations (name) VALUES ('0089_documents_object_storage.sql');
INSERT INTO __migrations (name) VALUES ('0090_rename_swap_to_replacement.sql');
INSERT INTO __migrations (name) VALUES ('0091_rename_swap_enum_values.sql');
INSERT INTO __migrations (name) VALUES ('0092_tap_in_out_owner_confirmation.sql');
INSERT INTO __migrations (name) VALUES ('0093_tap_in_out_mode.sql');
INSERT INTO __migrations (name) VALUES ('0094_tap_in_counts_as_hours.sql');
INSERT INTO __migrations (name) VALUES ('0095_rename_owner_to_admin.sql');
INSERT INTO __migrations (name) VALUES ('0096_add_manager_role.sql');
INSERT INTO __migrations (name) VALUES ('0097_rename_salle_to_floor.sql');
INSERT INTO __migrations (name) VALUES ('0098_documents_phase_e.sql');
INSERT INTO __migrations (name) VALUES ('0099_cron_runs.sql');
INSERT INTO __migrations (name) VALUES ('0100_restaurants_siret.sql');
INSERT INTO __migrations (name) VALUES ('0100_user_dpae_fields.sql');
INSERT INTO __migrations (name) VALUES ('0101_onboarding_tokens.sql');
INSERT INTO __migrations (name) VALUES ('0101_restaurants_whatsapp_bot_locale.sql');
INSERT INTO __migrations (name) VALUES ('0102_address_split_admin_alerts.sql');
INSERT INTO __migrations (name) VALUES ('0102_open_shifts.sql');
INSERT INTO __migrations (name) VALUES ('0103_dossier_reminder_timestamp.sql');
INSERT INTO __migrations (name) VALUES ('0104_documents_admin_review.sql');
INSERT INTO __migrations (name) VALUES ('0105_replacement_reply_deadline.sql');
INSERT INTO __migrations (name) VALUES ('0106_planning_publication_workflow.sql');
INSERT INTO __migrations (name) VALUES ('0107_open_shift_sequential_solicitation.sql');
INSERT INTO __migrations (name) VALUES ('0108_legal_acceptances.sql');
INSERT INTO __migrations (name) VALUES ('0109_user_notice_whatsapp_consent.sql');
INSERT INTO __migrations (name) VALUES ('0110_onboarding_default_stable_style.sql');
INSERT INTO __migrations (name) VALUES ('0111_backfill_worker_subroles.sql');
INSERT INTO __migrations (name) VALUES ('0112_subscription_cancellation_details.sql');
INSERT INTO __migrations (name) VALUES ('0113_timeclock_admin_confirmation.sql');
INSERT INTO __migrations (name) VALUES ('0114_staffing_analysis_cache.sql');
INSERT INTO __migrations (name) VALUES ('0115_monthly_digest_silae_toggle.sql');
INSERT INTO __migrations (name) VALUES ('0115_multi_restaurant_foundation.sql');
INSERT INTO __migrations (name) VALUES ('0116_active_restaurant_context.sql');
INSERT INTO __migrations (name) VALUES ('0117_owner_legal_acceptances.sql');
INSERT INTO __migrations (name) VALUES ('0118_whatsapp_context_sessions.sql');
INSERT INTO __migrations (name) VALUES ('0119_onboarding_token_restaurant_context.sql');
INSERT INTO __migrations (name) VALUES ('0120_worker_share_authorizations.sql');
INSERT INTO __migrations (name) VALUES ('0121_split_table_scope_metadata.sql');
INSERT INTO __migrations (name) VALUES ('0122_backfill_split_table_scope_metadata.sql');
INSERT INTO __migrations (name) VALUES ('0123_fr_hcr_default_contract_hours.sql');
INSERT INTO __migrations (name) VALUES ('0124_worker_multi_restaurant_opt_in_default.sql');

PRAGMA foreign_keys = ON;
