import { Database } from "bun:sqlite";
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";

const apiDir = new URL("..", import.meta.url).pathname;
const drizzleDir = join(apiDir, "drizzle");
const baselinePath = join(apiDir, "drizzle", "baseline", "current.sql");

const ignoredSqliteObjects = new Set(["sqlite_sequence"]);

function migrationFiles(): string[] {
  return readdirSync(drizzleDir)
    .filter((file) => file.endsWith(".sql"))
    .sort();
}

function applyMigrations(db: Database, files = migrationFiles()) {
  db.exec("PRAGMA journal_mode = WAL;");
  db.exec("PRAGMA foreign_keys = ON;");
  db.exec(`
    CREATE TABLE IF NOT EXISTS __migrations (
      name TEXT PRIMARY KEY,
      applied_at TEXT NOT NULL DEFAULT (datetime('now'))
    )
  `);

  for (const file of files) {
    const sql = readFileSync(join(drizzleDir, file), "utf8");
    db.exec(sql);
    db.run("INSERT INTO __migrations (name) VALUES (?)", [file]);
  }
}

function quoteSql(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function createBaselineSql(source: Database): string {
  const objects = source.query(`
    SELECT type, name, tbl_name AS tblName, sql
    FROM sqlite_master
    WHERE sql IS NOT NULL
      AND name NOT LIKE 'sqlite_%'
    ORDER BY
      CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 WHEN 'trigger' THEN 2 WHEN 'view' THEN 3 ELSE 4 END,
      name
  `).all() as Array<{ type: string; name: string; tblName: string; sql: string }>;

  const lines: string[] = [
    "-- Current Comptoir SQLite baseline.",
    "-- Generated by: bun packages/api/scripts/db-baseline.ts generate",
    "-- Do not edit manually; update through migrations, then regenerate.",
    "PRAGMA foreign_keys = OFF;",
    "",
  ];

  for (const object of objects) {
    if (ignoredSqliteObjects.has(object.name)) continue;
    const sql = object.name === "__migrations"
      ? object.sql.replace(/^CREATE TABLE/i, "CREATE TABLE IF NOT EXISTS")
      : object.sql;
    lines.push(`${sql};`);
    lines.push("");
  }

  lines.push("DELETE FROM __migrations;");
  const files = migrationFiles();
  for (const file of files) {
    lines.push(`INSERT INTO __migrations (name) VALUES (${quoteSql(file)});`);
  }
  lines.push("");
  lines.push("PRAGMA foreign_keys = ON;");
  lines.push("");

  return lines.join("\n");
}

function schemaSignature(db: Database) {
  return db.query(`
    SELECT type, name, tbl_name AS tblName, sql
    FROM sqlite_master
    WHERE sql IS NOT NULL
      AND name NOT LIKE 'sqlite_%'
    ORDER BY type, name
  `).all();
}

function assertEquivalent(left: Database, right: Database) {
  const leftSig = JSON.stringify(schemaSignature(left), null, 2);
  const rightSig = JSON.stringify(schemaSignature(right), null, 2);
  if (leftSig !== rightSig) {
    writeFileSync("/tmp/comptoir-db-baseline-left.json", leftSig);
    writeFileSync("/tmp/comptoir-db-baseline-right.json", rightSig);
    throw new Error("Baseline schema differs from historical migrations. See /tmp/comptoir-db-baseline-left.json and /tmp/comptoir-db-baseline-right.json");
  }
}

function tempDbPath(label: string): string {
  return join(tmpdir(), `comptoir-${label}-${crypto.randomUUID()}.db`);
}

function generate() {
  const dbPath = tempDbPath("historical");
  const db = new Database(dbPath);
  try {
    applyMigrations(db);
    mkdirSync(dirname(baselinePath), { recursive: true });
    writeFileSync(baselinePath, createBaselineSql(db));
    console.log(`Generated ${baselinePath}`);
  } finally {
    db.close();
    rmSync(dbPath, { force: true });
    rmSync(`${dbPath}-shm`, { force: true });
    rmSync(`${dbPath}-wal`, { force: true });
  }
}

function verify() {
  const historicalPath = tempDbPath("historical");
  const baselineDbPath = tempDbPath("baseline");
  const historical = new Database(historicalPath);
  const baseline = new Database(baselineDbPath);
  try {
    applyMigrations(historical);
    baseline.exec(readFileSync(baselinePath, "utf8"));
    assertEquivalent(historical, baseline);
    console.log("Baseline schema matches historical migrations.");
  } finally {
    historical.close();
    baseline.close();
    for (const path of [historicalPath, baselineDbPath]) {
      rmSync(path, { force: true });
      rmSync(`${path}-shm`, { force: true });
      rmSync(`${path}-wal`, { force: true });
    }
  }
}

const command = process.argv[2] ?? "verify";
if (command === "generate") generate();
else if (command === "verify") verify();
else {
  console.error("Usage: bun packages/api/scripts/db-baseline.ts [generate|verify]");
  process.exit(2);
}
